In [67]:
import numpy as np
import time

In [8]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [9]:
#execution performance
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list =[ x**2 for x in py_list]
end = time.time()
print(f"time taken to complete the execution {end-start} seconds")

#numpy array
py_array = np.array(py_list)
start =time.time()
sq_array = py_array**2
end =time.time()
print(f"time taken to complete the execution {end-start} seconds")



time taken to complete the execution 0.04228520393371582 seconds
time taken to complete the execution 0.0013523101806640625 seconds


In [12]:
arr = np.array([1,2,3,4,5,"prime"])
print(arr,type(arr),arr.shape)

['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> (6,)


In [13]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print(arr2d,type(arr2d),arr2d.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> (3, 3)


In [19]:
#create 
arr2dd = np.zeros((3,3)) #prefill
print(arr2dd,arr2d.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] (3, 3)


In [20]:
#create 
arr2dd = np.ones((3,3)) #pefill
print(arr2dd,arr2d.shape)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] (3, 3)


In [21]:
#prefill with particular value
arr2dd = np.full((3,4),100)
print(arr2dd,arr2d.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 3)


In [22]:
#prefill with particular value
arr2dd = np.full((3,4),100)
print(arr2dd,arr2d.shape)

[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 3)


In [26]:
#prefill with particular value
arr2dd = np.eye(3) #identity matrix
print(arr2dd,arr2d.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)


In [30]:
#range function range(start,end,next)
arr2dd = np.arange(1,11,2)
print(arr2dd,arr2d.shape)

[1 3 5 7 9] (3, 3)


In [32]:
#evenly spaced array
arr2dd = np.linspace(1,100,4)
print(arr2dd,arr2d.shape)

[  1.  34.  67. 100.] (3, 3)


In [5]:
#property
arr = np.array([1,2,3,4,5])
print(arr.shape)

(5,)


In [12]:
#2 array size mXn
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

#type casting 
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [13]:
# reshaping an array  # operation on array 
arr= np.array([[1,2,3],[4,5,6]])
print(arr)


[[1 2 3]
 [4 5 6]]


In [14]:
print(arr,arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [17]:
reshaped = arr.reshape((3,2))
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [18]:
print(reshaped.size)

6


In [19]:
print(reshaped.shape)

(3, 2)


In [20]:
flattend_arr = arr.flatten()
print(flattend_arr)

[1 2 3 4 5 6]


In [22]:
print(flattend_arr.shape)

(6,)


In [25]:
#indexing on array
arr= np.array([1,2,3,4,5])
print(arr[0])
print(arr[3])

1
4


In [27]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1][1])

[[1 2 3]
 [4 5 6]]
5


In [30]:
#fancy indexing 
arr = np.array([1,2,3,4,5  ])
idx = [0,1,3]
print(arr[idx])

[1 2 4]


In [32]:
# boolean indexing
arr = np.array([1,2,3,4,5])
print(arr[arr>3])
print(arr[arr %2 == 0 ])

[4 5]
[2 4]


In [37]:
# slicing operation in numpy arrays 
arr = np.array([1,2,3,4,5])
print(arr[1:4])
print(arr[1:4:2]) # start , end , steps
print(arr[::])
print(arr[::2])  # array mae copy nai create hota view hota ha .copy()

[2 3 4]
[2 4]
[1 2 3 4 5]
[1 3 5]


In [38]:
# numpy data typesss


In [45]:
# multi- dimensional array 

arr_2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2D)
print(np.sum(arr_2D))


sum_of_columns = np.sum(arr_2D, axis = 0 )
print(sum_of_columns) # columns


sum_of_rows = np.sum(arr_2D, axis = 1 )
print(sum_of_rows)  # rows


#slice in 2d array 
print(arr_2D[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [52]:
# 3d array 
arr_3D = np.array([[[1,2],[3,4],[5,6]],
                [[7,8],[9,10],[11,12]]]) # 2 X 3 X 2
print(arr_3D,arr_3D.shape,arr_3D.size)


# indexing 
print(arr_3D[0,1,1])


#slicing
print(arr_3D[:,0,:]) #first row from the both layers
print(arr_3D[:,:,0]) #first  col  from the both layers

arr_3D[:,0,:] = 99 
print(arr_3D)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2) 12
4
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[[99 99]
  [ 3  4]
  [ 5  6]]

 [[99 99]
  [ 9 10]
  [11 12]]]


In [55]:
# vectorization and broadcasting


# vectorization 
arr = np.array([1,2,3,4,5])
print(arr**2)

arr1 = np.array([1,2,3,4,5])
print(arr++2)

print(arr+arr1)


[ 1  4  9 16 25]
[3 4 5 6 7]
[ 2  4  6  8 10]


In [56]:
# broadcasting
# scaling our array without using extra memory
print(arr + 5) # behind the scene broadcasting


[ 6  7  8  9 10]


In [59]:
arr = np.array([1,2,3,4,5])
arr1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])  # broadcast 

print(arr.shape)
print(arr1.shape)

print(arr + arr1)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


In [66]:
#vector normailization

# standard normaization

#(arr-mean)/std dev -- jab ham yae formula use karta tou hamara vector normailize hojata ha

arr = np.array([[1,2],[3,4]])
mean = np.mean(arr)
standard_dev = np.std(arr)

normalize_arr = (arr-mean)/standard_dev
print(normalize_arr)

print(mean)
print(standard_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [81]:
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.max(arr))
print(np.min(arr))
print(np.prod(arr))
print(np.argmin(arr))
print(np.argmax(arr)) # yae dono index return kart aha

print(np.mean(arr))
print(np.std(arr))
print(np.median(arr))
print(np.var(arr))


#power function
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))





15
5
1
120
0
4
3.0
1.4142135623730951
3.0
2.0
[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [82]:
#log related fucntion

print(np.log(arr))
print(np.log10(arr))
print(np.log2(arr))

print(np.exp(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [86]:
#rounding function

print(np.round(3.14))
print(np.round(3.94))

print(np.ceil(3.14))
print(np.floor(3.14))

3.0
4.0
4.0
3.0
