In [2]:
import numpy as np



In [3]:
a = np.array([1,2,3,4])
print(a)



[1 2 3 4]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.full((3,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(arr.shape)

(3, 3)


In [16]:
print(arr.size)

9


In [17]:
print(arr.dtype)

int64


In [18]:
print(arr.ndim)

2


In [19]:
print(arr[0])

[1 2 3]


In [20]:
print(arr[1:2])

[[4 5 6]]


In [21]:
arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[1:4])

10
[20 30 40]


In [22]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[0,1])
print(arr[:,1])


2
[2 5]


In [23]:
# typecasting
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]] float64


In [24]:
# aggreagate function
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

15
3.0
5
1
1.4142135623730951


In [25]:
arr = np.array([1,2,3])

print(arr + 10)

[11 12 13]


In [28]:
c = np.array([1,2,3,4,5,6,7,8,9,10])


In [42]:
print(c)
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [32]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
arr = [[1,2,3],
 [4,5,6],
 [7,8,9]]

In [34]:
print(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [37]:
print(arr[1:2])

[[4, 5, 6]]


In [38]:
arr = [10,20,30,40]

In [40]:
print(np.sum(arr))

100


In [41]:
print(np.mean(arr))

25.0


In [45]:
arr =np.zeros((4,4))

In [46]:
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
#2️⃣ Create array [5,10,15,20,25] using arange

arr = np.arange(5,30,5)

In [50]:
print(arr)

[ 5 10 15 20 25]


In [52]:
arr = np.array([3,7,2,9,4])

In [53]:
print(np.max(arr))

9


In [54]:
#4️⃣ Multiply array

#[1,2,3]

#by 5 using broadcasting

arr = np.array([1,2,3])

In [55]:
print(arr)

[1 2 3]


In [56]:
print(arr * 5)

[ 5 10 15]


In [57]:
# reshape
arr = np.arange(1,10)
print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

32


In [59]:
arr = np.array([[1,2,3],[4,5,6]])

print(np.sum(arr, axis=0))  # column sum
print(np.sum(arr, axis=1))  # row sum

[5 7 9]
[ 6 15]
