In [2]:
import numpy as np



In [3]:
a = np.array([1,2,3,4])
print(a)



[1 2 3 4]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [9]:
np.full((3,4),100)

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
arr = np.array(
    [[1,2,3],
    [4,5,6],
    [7,8,9]]
)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
print(arr.shape)

(3, 3)


In [16]:
print(arr.size)

9


In [17]:
print(arr.dtype)

int64


In [18]:
print(arr.ndim)

2


In [19]:
print(arr[0])

[1 2 3]


In [20]:
print(arr[1:2])

[[4 5 6]]


In [21]:
arr = np.array([10,20,30,40,50])

print(arr[0])
print(arr[1:4])

10
[20 30 40]


In [22]:
arr = np.array([[1,2,3],
                [4,5,6]])

print(arr[0,1])
print(arr[:,1])


2
[2 5]


In [23]:
# typecasting
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

[[1. 2. 3.]
 [4. 5. 6.]] float64


In [24]:
# aggreagate function
arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))

15
3.0
5
1
1.4142135623730951


In [25]:
arr = np.array([1,2,3])

print(arr + 10)

[11 12 13]


In [28]:
c = np.array([1,2,3,4,5,6,7,8,9,10])


In [42]:
print(c)
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [30]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [32]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [33]:
arr = [[1,2,3],
 [4,5,6],
 [7,8,9]]

In [34]:
print(arr)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [37]:
print(arr[1:2])

[[4, 5, 6]]


In [38]:
arr = [10,20,30,40]

In [40]:
print(np.sum(arr))

100


In [41]:
print(np.mean(arr))

25.0


In [45]:
arr =np.zeros((4,4))

In [46]:
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [49]:
#2️⃣ Create array [5,10,15,20,25] using arange

arr = np.arange(5,30,5)

In [50]:
print(arr)

[ 5 10 15 20 25]


In [52]:
arr = np.array([3,7,2,9,4])

In [53]:
print(np.max(arr))

9


In [54]:
#4️⃣ Multiply array

#[1,2,3]

#by 5 using broadcasting

arr = np.array([1,2,3])

In [55]:
print(arr)

[1 2 3]


In [56]:
print(arr * 5)

[ 5 10 15]


In [57]:
# reshape
arr = np.arange(1,10)
print(arr.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b))

32


In [59]:
arr = np.array([[1,2,3],[4,5,6]])

print(np.sum(arr, axis=0))  # column sum
print(np.sum(arr, axis=1))  # row sum

[5 7 9]
[ 6 15]


In [60]:
# PANDAS
import pandas as pd

In [64]:
info = {
    "Name " : ["Harsh","Shreya","Tulika"],
    "CGPA " : ["9.5","8.9","9.1"]
}


In [65]:
df = pd.DataFrame(info)

In [66]:
print(df)

    Name  CGPA 
0   Harsh   9.5
1  Shreya   8.9
2  Tulika   9.1


In [67]:
s = pd.Series([1,2,3,4,5])

In [69]:
print(s)


0    1
1    2
2    3
3    4
4    5
dtype: int64


In [70]:
print(type(s) , type(df))

<class 'pandas.Series'> <class 'pandas.DataFrame'>


In [72]:
print(s[0])
print(s[3])

1
4


In [78]:
s = pd.Series(["23" , "25" , "18" , "45"], index = ["Adam","Eva" , "Finch" , "Sachin"])

In [79]:
print(s)

Adam      23
Eva       25
Finch     18
Sachin    45
dtype: str


In [81]:
print(s["Adam"])

23


In [82]:
print(s.index)

Index(['Adam', 'Eva', 'Finch', 'Sachin'], dtype='str')


In [83]:
print( df.index)

RangeIndex(start=0, stop=3, step=1)


In [84]:
print(s.index)

Index(['Adam', 'Eva', 'Finch', 'Sachin'], dtype='str')


In [85]:
print(df.columns)

Index(['Name ', 'CGPA '], dtype='str')


In [89]:
df1 = pd.DataFrame(np.array([[1,2,3],[4,5,6]]),columns=["A","B","C"])

In [90]:
print(df1)

   A  B  C
0  1  2  3
1  4  5  6


In [91]:
df = pd.read_csv("employee_data.csv")

In [92]:
print(df)

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000


In [93]:
df.head()

,ID,Name,Age,Department,Salary
0,1,Alice,25,HR,55000
1,2,Bob,32,IT,72000
2,3,Charlie,28,Finance,48000
3,4,David,45,Marketing,91000
4,5,Eva,38,IT,65000


In [94]:
df.tail()


,ID,Name,Age,Department,Salary
5,6,Frank,29,Finance,50000
6,7,Grace,41,HR,82000
7,8,Hannah,26,Marketing,47000
8,9,Ian,35,IT,75000
9,10,Julia,30,Finance,60000


In [95]:
df.sample()

,ID,Name,Age,Department,Salary
2,3,Charlie,28,Finance,48000


In [96]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str  
 2   Age         10 non-null     int64
 3   Department  10 non-null     str  
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 532.0 bytes


In [98]:
df.shape

(10, 5)

In [99]:
df.describe()

,ID,Age,Salary
count,10.00000,10.000000,10.000000
mean,5.50000,32.900000,64500.000000
std,3.02765,6.674162,15182.226451
min,1.00000,25.000000,47000.000000
25%,3.25000,28.250000,51250.000000
50%,5.50000,31.000000,62500.000000
75%,7.75000,37.250000,74250.000000
max,10.00000,45.000000,91000.000000


In [100]:
df.columns

Index(['ID', 'Name', 'Age', 'Department', 'Salary'], dtype='str')

In [103]:
df.nunique()

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [104]:
df.loc[0]

ID                1
Name          Alice
Age              25
Department       HR
Salary        55000
Name: 0, dtype: object

In [105]:
df.iloc[0]

ID                1
Name          Alice
Age              25
Department       HR
Salary        55000
Name: 0, dtype: object

In [106]:
df.iloc[0:2]

,ID,Name,Age,Department,Salary
0,1,Alice,25,HR,55000
1,2,Bob,32,IT,72000


In [108]:
df[df["Name"] == "Alice"]

,ID,Name,Age,Department,Salary
0,1,Alice,25,HR,55000


In [110]:
df.isnull()

,ID,Name,Age,Department,Salary
0,False,False,False,False,False
1,False,False,False,False,False
2,False,False,False,False,False
3,False,False,False,False,False
4,False,False,False,False,False
5,False,False,False,False,False
6,False,False,False,False,False
7,False,False,False,False,False
8,False,False,False,False,False
9,False,False,False,False,False


In [111]:
df.dropna()

,ID,Name,Age,Department,Salary
0,1,Alice,25,HR,55000
1,2,Bob,32,IT,72000
2,3,Charlie,28,Finance,48000
3,4,David,45,Marketing,91000
4,5,Eva,38,IT,65000
5,6,Frank,29,Finance,50000
6,7,Grace,41,HR,82000
7,8,Hannah,26,Marketing,47000
8,9,Ian,35,IT,75000
9,10,Julia,30,Finance,60000


In [112]:
age_mean = df["Age"].mean()

In [113]:
print(age_mean)

32.9


In [114]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [115]:
df.dtypes

ID            int64
Name            str
Age           int64
Department      str
Salary        int64
dtype: object

In [119]:
df["Name"] = df["Name"].str.lower()

In [120]:
df

,ID,Name,Age,Department,Salary
0,1,alice,25,HR,55000
1,2,bob,32,IT,72000
2,3,charlie,28,Finance,48000
3,4,david,45,Marketing,91000
4,5,eva,38,IT,65000
5,6,frank,29,Finance,50000
6,7,grace,41,HR,82000
7,8,hannah,26,Marketing,47000
8,9,ian,35,IT,75000
9,10,julia,30,Finance,60000


In [123]:
# df["age"].hist()

In [124]:
iris = pd.read_csv("IRIS.csv")

In [125]:
print(iris)

     sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]


In [126]:
iris.head()


,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa


In [133]:
iris.head(10)

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
5,5.4,3.9,1.7,0.4,Iris-setosa
6,4.6,3.4,1.4,0.3,Iris-setosa
7,5.0,3.4,1.5,0.2,Iris-setosa
8,4.4,2.9,1.4,0.2,Iris-setosa
9,4.9,3.1,1.5,0.1,Iris-setosa


In [134]:
iris.shape

(150, 5)

In [135]:
iris.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [136]:
iris.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.054000,3.758667,1.198667
std,0.828066,0.433594,1.764420,0.763161
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [138]:
print(iris.mean(numeric_only = True))

sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
dtype: float64


In [140]:
print(iris.max(numeric_only = True))

sepal_length    7.9
sepal_width     4.4
petal_length    6.9
petal_width     2.5
dtype: float64


In [154]:
#ques1 - select only rows where petal_length > 4.5 , species = " Iris-virginica"

select_row = iris [(iris["petal_length"] > 6.5 ) & (iris["species"] ==  "Iris-virginica") ]



In [155]:
print(select_row)

     sepal_length  sepal_width  petal_length  petal_width         species
105           7.6          3.0           6.6          2.1  Iris-virginica
117           7.7          3.8           6.7          2.2  Iris-virginica
118           7.7          2.6           6.9          2.3  Iris-virginica
122           7.7          2.8           6.7          2.0  Iris-virginica


In [156]:
# group by and compute 
# avergae sepal_ length , maximum petal lenght , standard deviation of sepal_width 

grouped = iris.groupby("species")

In [157]:
result = grouped.agg(
    avg_sepal_length = ("sepal_length","mean"),
    max_petal_length = ("petal_length","max"),
    std_sepal_width = ("sepal_width","std"))
    

In [158]:
print(result)

                 avg_sepal_length  max_petal_length  std_sepal_width
species                                                             
Iris-setosa                 5.006               1.9         0.381024
Iris-versicolor             5.936               5.1         0.313798
Iris-virginica              6.588               6.9         0.322497


In [161]:
iris["petal_ratio"] = iris["petal_length"]/iris["petal_width"]
group = iris.groupby("species")

avg_petal_ratio = group.agg(
    average = ("petal_ratio","mean")
)

In [ ]:
print(avg_petal_ratio)